"""add was_postponed to orders

Revision ID: 2ead1b4331ae
Revises: d40de3fd879f
Create Date: 2026-06-19 22:57:25.932108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ead1b4331ae'
down_revision: Union[str, Sequence[str], None] = 'd40de3fd879f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('was_postponed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'was_postponed')
    # ### end Alembic commands ###
