"""add pickup fields and stop_type

Revision ID: 5f70c75983b1
Revises: 28294280a7c0
Create Date: 2026-04-26 13:21:46.163832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f70c75983b1'
down_revision: Union[str, Sequence[str], None] = '28294280a7c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address_pickup', sa.Text(), nullable=False))
    op.add_column('orders', sa.Column('pickup_lat', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('orders', sa.Column('pickup_lon', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('orders', sa.Column('delivery_lat', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('orders', sa.Column('delivery_lon', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('orders', sa.Column('pickup_time_window_start', sa.Time(), nullable=True))
    op.add_column('orders', sa.Column('pickup_time_window_end', sa.Time(), nullable=True))
    op.add_column('orders', sa.Column('delivery_time_window_start', sa.Time(), nullable=True))
    op.add_column('orders', sa.Column('delivery_time_window_end', sa.Time(), nullable=True))
    op.drop_column('orders', 'lon')
    op.drop_column('orders', 'lat')
    op.drop_column('orders', 'time_window_start')
    op.drop_column('orders', 'time_window_end')
    # Creează mai întâi tipul enum în PostgreSQL, apoi adaugă coloana
    stoptypeenum = sa.Enum('PICKUP', 'DELIVERY', name='stoptypeenum')
    stoptypeenum.create(op.get_bind(), checkfirst=True)
    op.add_column('trip_stops', sa.Column('stop_type', stoptypeenum, nullable=False))    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_stops', 'stop_type')
    op.add_column('orders', sa.Column('time_window_end', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('time_window_start', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('lat', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('lon', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True))
    op.drop_column('orders', 'delivery_time_window_end')
    op.drop_column('orders', 'delivery_time_window_start')
    op.drop_column('orders', 'pickup_time_window_end')
    op.drop_column('orders', 'pickup_time_window_start')
    op.drop_column('orders', 'delivery_lon')
    op.drop_column('orders', 'delivery_lat')
    op.drop_column('orders', 'pickup_lon')
    op.drop_column('orders', 'pickup_lat')
    op.drop_column('orders', 'address_pickup')
    # ### end Alembic commands ###
