"""add order problematic fields

Revision ID: 69a58d7c6d31
Revises: 5a6c06d0e0b9
Create Date: 2026-05-24 21:44:26.605488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a58d7c6d31'
down_revision: Union[str, Sequence[str], None] = '5a6c06d0e0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_problematic', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('orders', sa.Column('problem_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'problem_reason')
    op.drop_column('orders', 'is_problematic')
    # ### end Alembic commands ###
