"""add structured address and depot fields

Revision ID: 7b382f799f84
Revises: fa4cf65d24b9
Create Date: 2026-06-18 00:43:23.061054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b382f799f84'
down_revision: Union[str, Sequence[str], None] = 'fa4cf65d24b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pickup_county', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('pickup_city', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('pickup_street', sa.String(length=150), nullable=True))
    op.add_column('orders', sa.Column('pickup_number', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('delivery_county', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('delivery_city', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('delivery_street', sa.String(length=150), nullable=True))
    op.add_column('orders', sa.Column('delivery_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_number')
    op.drop_column('orders', 'delivery_street')
    op.drop_column('orders', 'delivery_city')
    op.drop_column('orders', 'delivery_county')
    op.drop_column('orders', 'pickup_number')
    op.drop_column('orders', 'pickup_street')
    op.drop_column('orders', 'pickup_city')
    op.drop_column('orders', 'pickup_county')
    # ### end Alembic commands ###
