"""add vehicle snapshot columns to trips

Revision ID: a1b2c3d4e5f6
Revises: 2ead1b4331ae
Create Date: 2026-07-03 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '2ead1b4331ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('vehicle_plate_snapshot', sa.String(), nullable=True))
    op.add_column('trips', sa.Column('vehicle_capacity_kg_snapshot', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('trips', sa.Column('vehicle_capacity_m3_snapshot', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'vehicle_capacity_m3_snapshot')
    op.drop_column('trips', 'vehicle_capacity_kg_snapshot')
    op.drop_column('trips', 'vehicle_plate_snapshot')
    # ### end Alembic commands ###
