"""add must_change_password and invited_by_id to users

Revision ID: cee57880f567
Revises: cbd5eeff1f35
Create Date: 2026-04-16 12:31:21.866353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee57880f567'
down_revision: Union[str, Sequence[str], None] = 'cbd5eeff1f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('invited_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['invited_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'invited_by_id')
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
