"""add depot fields to company

Revision ID: fa4cf65d24b9
Revises: 1427bdb1f6fd
Create Date: 2026-06-17 10:39:02.932132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4cf65d24b9'
down_revision: Union[str, Sequence[str], None] = '1427bdb1f6fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('depot_county', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('depot_city', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('depot_street', sa.String(length=150), nullable=True))
    op.add_column('companies', sa.Column('depot_number', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('depot_lat', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('companies', sa.Column('depot_lon', sa.Numeric(precision=10, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'depot_lon')
    op.drop_column('companies', 'depot_lat')
    op.drop_column('companies', 'depot_number')
    op.drop_column('companies', 'depot_street')
    op.drop_column('companies', 'depot_city')
    op.drop_column('companies', 'depot_county')
    # ### end Alembic commands ###
